require: rubocop-rails

AllCops:
  Exclude:
    - db/schema.rb
    - bin/**/*
    - tmp/**/*
    - vendor/**/*

Style/Documentation:
  Enabled: false

Rails/HasAndBelongsToMany:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'db/migrate/**/*.rb'
    - 'config/environments/**'
    - 'config/routes.rb'

Metrics/AbcSize:
  Exclude:
    - 'db/migrate/**/*.rb'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/**/*.rb'

Rails/Output:
  Exclude:
    - 'db/seeds/**/*.rb'
