default: &default
  adapter: postgresql
  encoding: unicode
  host: localhost
  password: postgres
  username: runner
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

test:
  <<: *default
  database: innocent_tech_app_test